// Code generated by 'malatd gen' command.
// DO NOT EDIT!

package args

import (
	"github.com/swxctx/malatd/binding"
)

// EmptyStruct alias of type struct {}
type EmptyStruct = binding.Empty

// PingArgsV1 alias of type binding.Empty
type PingArgsV1 = binding.Empty

// PingResultV1 alias of type binding.Empty
type PingResultV1 = binding.Empty
