// Code generated by 'malatd gen' command.
// The temporary code used to ensure successful compilation!
// When the project is completed, it should be removed!

package logic

//import (
//	td "github.com/swxctx/malatd"
//	"github.com/txxzx/goAi/args"
//)
//
//// Do handler
//func V1_Chat_Do(ctx *td.Context, arg *args.ChatDoArgsV1) (*args.ChatDoResultV1, *td.Rerror) {
//	return new(args.ChatDoResultV1), nil
//}
