// Code generated by 'malatd gen' command.
// The temporary code used to ensure successful compilation!
// When the project is completed, it should be removed!

package logic

import (
	td "github.com/swxctx/malatd"
	"github.com/txxzx/goAi/args"
)

// Ping handler
func V1_Test_Ping(ctx *td.Context, arg *args.PingArgsV1) (*args.PingResultV1, *td.Rerror) {
	return new(args.PingResultV1), nil
}
